version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: jogo_backend
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:3001"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    command: ["node", "src/server.js"]
    working_dir: /app

  frontend:
    build:
      context: ./template
      dockerfile: Dockerfile.frontend
    container_name: jogo_frontend
    env_file:
      - .env
    ports:
      - "3000:4173"
    volumes:
      - ./template:/app
    stdin_open: true
    tty: true

  postgres:
    image: postgres:15
    container_name: jogo_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
