version: "3.9"

services:
  backend:
    build: ./backend
    container_name: jogo_backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${BACKEND_PORT}:3001"
    volumes:
      - ../backend:/app
    depends_on:
      - postgres
    command: ["node", "index.js"]
    working_dir: /app

  frontend:
    build: ./frontend
    container_name: jogo_frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ../frontend:/app
    stdin_open: true
    tty: true
    working_dir: /app

  postgres:
    image: postgres:15
    container_name: jogo_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
